"""
Tool for writing the end-of-day diary file.

Receives the markdown content generated by the LLM after cronos_fine_giornata
and writes it to the correct diary file. Optionally writes the companion
standup.md narrative in the same day folder (see get_standup_path). Optionally
commits and pushes the changes to the diary git repository based on config
settings.
"""

import subprocess
from typing import Optional

from mcp_cronos.config import get_diario_path, load_config
from mcp_cronos.tools.prepara_domani import prepara_domani
from mcp_cronos.utils.dates import (
    ensure_directory_exists,
    get_standup_path,
    get_today,
    parse_date,
    resolve_fine_giornata_path,
)


def _git_commit_and_push(file_date) -> dict:
    """
    Stage the whole diary, commit, and optionally push to the remote repository.

    Stages everything with ``git add -A`` so the full day's work — raw entries,
    todos, blockers, the end-of-day file, and the prepared next-day files — is
    committed and pushed together in a single operation.

    Respects the config settings: git_enabled, auto_push, and commit_message.
    When git is disabled via config, returns immediately with {"git": "disabled"}.

    Args:
        file_date: Date of the diary entry (used in commit message).

    Returns:
        Dict with git operation status and details.
    """
    config = load_config()
    if not config.git_enabled:
        return {"git": "disabled"}

    diario_root = str(get_diario_path())

    git_result = {"git_add": None, "git_commit": None, "git_push": None}

    try:
        # Stage the entire diary so raw entries, todos, and next-day files are included.
        subprocess.run(
            ["git", "add", "-A"],
            cwd=diario_root,
            capture_output=True,
            text=True,
            check=True,
        )
        git_result["git_add"] = "ok"

        # git commit with configurable message
        commit_msg = config.commit_message.format(date=file_date)
        result = subprocess.run(
            ["git", "commit", "-m", commit_msg],
            cwd=diario_root,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            git_result["git_commit"] = "ok"
        elif "nothing to commit" in result.stdout or "nothing to commit" in result.stderr:
            git_result["git_commit"] = "nessuna modifica da committare"
            return git_result
        else:
            git_result["git_commit"] = f"errore: {result.stderr.strip()}"
            return git_result

        # git push (only if auto_push is enabled)
        if not config.auto_push:
            git_result["git_push"] = "skipped (auto_push disabled)"
            return git_result

        result = subprocess.run(
            ["git", "push"],
            cwd=diario_root,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            git_result["git_push"] = "ok"
        else:
            git_result["git_push"] = f"errore: {result.stderr.strip()}"

    except FileNotFoundError:
        git_result["git_add"] = "errore: git non trovato"
    except subprocess.CalledProcessError as e:
        git_result["git_add"] = f"errore: {e.stderr.strip()}"

    return git_result


def _scrivi_standup(file_date, contenuto_standup: Optional[str]) -> dict:
    """
    Write standup.md next to fine-giornata.md when contenuto_standup is usable.

    A blank or whitespace-only value is treated the same as omitting the
    parameter: it never produces an empty file on disk, and the caller gets
    the same "not provided" warning either way.

    Args:
        file_date: Date of the closure being written (drives the day folder).
        contenuto_standup: Markdown content for standup.md, or None/blank.

    Returns:
        Dict with 'scritto' (bool) and either 'file' (path written) or
        'avviso' (message explaining the file was not produced).
    """
    if contenuto_standup is None or not contenuto_standup.strip():
        return {
            "scritto": False,
            "avviso": (
                "standup.md non e' stato prodotto: e' atteso a ogni chiusura di "
                "giornata. Passa contenuto_standup a cronos_scrivi_fine_giornata "
                "nella stessa chiamata."
            ),
        }

    standup_path = get_standup_path(file_date)
    ensure_directory_exists(standup_path)
    standup_path.write_text(contenuto_standup, encoding="utf-8")
    return {"scritto": True, "file": str(standup_path)}


def scrivi_fine_giornata(
    contenuto: str,
    data: Optional[str] = None,
    contenuto_todo: Optional[str] = None,
    contenuto_standup: Optional[str] = None,
) -> dict:
    """
    Writes the end-of-day file and commits/pushes it to the diary repository.

    Args:
        contenuto: Contenuto markdown completo del file (con tutte le sezioni)
        data: Data del file YYYY-MM-DD (default: oggi)
        contenuto_todo: Se fornito, prepara la cartella del prossimo giorno
            lavorativo con questo contenuto todo.md, richiamando prepara_domani.
            Il risultato viene restituito sotto la chiave 'prepara_domani'.
        contenuto_standup: Se fornito (e non vuoto), scrive standup.md nella
            stessa cartella giornaliera di fine-giornata.md. Il risultato
            viene restituito sotto la chiave 'standup'; se omesso o vuoto,
            'standup' riporta un avviso invece di scrivere il file.

    Returns:
        Dict con risultato operazione, esito standup.md e stato git
    """
    if data:
        try:
            file_date = parse_date(data)
        except ValueError as e:
            return {"errore": str(e)}
    else:
        file_date = get_today()

    file_path = resolve_fine_giornata_path(file_date)
    ensure_directory_exists(file_path)

    file_path.write_text(contenuto, encoding="utf-8")

    risultato = {
        "successo": True,
        "file": str(file_path),
        "data": str(file_date),
        "dimensione": len(contenuto),
        "messaggio": f"File di fine giornata scritto per {file_date}",
    }
    risultato["standup"] = _scrivi_standup(file_date, contenuto_standup)
    # Prepare next day BEFORE committing so its files join the same end-of-day commit.
    if contenuto_todo is not None:
        try:
            risultato["prepara_domani"] = prepara_domani(contenuto_todo)
        except OSError as exc:
            risultato["prepara_domani"] = {"successo": False, "errore": str(exc)}
    # Commit and push the whole diary (entire day + prepared next day + standup).
    risultato["git"] = _git_commit_and_push(file_date)
    return risultato
