"""
Tool for generating discursive standup summaries.

Reads the diary and returns entry content along with style instructions
for generating the message. The final summary is generated by the LLM,
not programmatically.
"""

from datetime import date, timedelta
from typing import Optional

from mcp_cronos.config import load_config
from mcp_cronos.i18n import get_language_pack
from mcp_cronos.template_loader import load_template
from mcp_cronos.utils.dates import get_date_range, get_file_path, get_today, parse_date
from mcp_cronos.utils.markdown import parse_diary_file


def _get_style_instructions() -> str:
    """Load the standup template from the template loader."""
    return load_template("standup")


def genera_riassunto_standup(
    data: Optional[str] = None,
    data_inizio: Optional[str] = None,
    data_fine: Optional[str] = None,
) -> dict:
    """
    Prepara i dati per generare un riassunto discorsivo per lo stand-up.

    Legge il diario per le date specificate e restituisce il contenuto
    completo delle entry insieme alle istruzioni di stile. Il riassunto
    viene generato dall'LLM sulla base di questi dati.

    Args:
        data: Data singola in formato YYYY-MM-DD (default: ultimo giorno lavorativo)
        data_inizio: Data inizio range in formato YYYY-MM-DD
        data_fine: Data fine range in formato YYYY-MM-DD

    Returns:
        Dict con contenuto del diario, istruzioni di stile e metadati
    """
    today = get_today()

    # Determina le date da leggere
    if data:
        try:
            dates_to_read = [parse_date(data)]
        except ValueError as e:
            return {"errore": str(e)}
    elif data_inizio and data_fine:
        try:
            start = parse_date(data_inizio)
            end = parse_date(data_fine)
            if start > end:
                return {"errore": "data_inizio deve essere precedente a data_fine"}
            dates_to_read = get_date_range(start, end)
        except ValueError as e:
            return {"errore": str(e)}
    else:
        # Default: ultimo giorno lavorativo
        dates_to_read = [_ultimo_giorno_lavorativo(today)]

    # Raccogli le entry con contenuto completo
    all_entries = []
    files_letti = []
    bloccanti = "Nessuno"

    for d in dates_to_read:
        file_path = get_file_path(d)
        if file_path.exists():
            diary = parse_diary_file(file_path)
            if diary:
                files_letti.append(str(d))
                bloccanti = diary.bloccanti
                for entry in diary.entries:
                    all_entries.append(
                        {
                            "data": str(d),
                            "progetto": entry.progetto,
                            "descrizione": entry.descrizione,
                            "contenuto_completo": entry.contenuto,
                            "richiesto_da": entry.richiesto_da,
                        }
                    )

    if not all_entries:
        return {
            "errore": "Nessuna entry trovata nel periodo specificato",
            "date_cercate": [str(d) for d in dates_to_read],
            "suggerimento": "Verifica che esistano file del diario per le date specificate",
        }

    # Determina il contesto temporale per il riassunto
    contesto = _determina_contesto_temporale(dates_to_read, today)

    return {
        "istruzioni_stile": _get_style_instructions(),
        "contesto": contesto,
        "entries": all_entries,
        "bloccanti": bloccanti,
        "periodo": {"da": str(dates_to_read[0]), "a": str(dates_to_read[-1])},
        "files_letti": files_letti,
        "num_entries": len(all_entries),
        "progetti": list(dict.fromkeys(e["progetto"] for e in all_entries)),
    }


def _ultimo_giorno_lavorativo(oggi: date) -> date:
    """
    Calcola l'ultimo giorno lavorativo (lun-ven) prima di oggi.

    Args:
        oggi: Data odierna

    Returns:
        Data dell'ultimo giorno lavorativo
    """
    giorno = oggi - timedelta(days=1)
    # Sabato (5) -> venerdi, Domenica (6) -> venerdi
    while giorno.weekday() >= 5:
        giorno -= timedelta(days=1)
    return giorno


def _determina_contesto_temporale(dates: list[date], oggi: date) -> str:
    """
    Build a human-readable temporal context string for the standup summary.

    Uses the language pack from the active config so weekday names, month names,
    and relative-time expressions match the configured locale.

    Args:
        dates: Dates covered by the summary.
        oggi: Today's date.

    Returns:
        Descriptive string (e.g. "Ieri (venerdi 6 marzo)").
    """
    config = load_config()
    pack = get_language_pack(config.lang)

    if len(dates) == 1:
        d = dates[0]
        diff = (oggi - d).days
        giorno_sett = pack.weekdays[d.weekday()]
        mese = pack.months[d.month - 1]

        date_detail = f"{giorno_sett} {d.day} {mese}"

        if diff == 1:
            return f"{pack.temporal['yesterday']} ({date_detail})"
        elif diff == 2:
            return f"{pack.temporal['day_before']} ({date_detail})"
        elif diff <= 4:
            last_wd = pack.temporal["last_weekday"].format(weekday=giorno_sett.capitalize())
            return f"{last_wd} ({d.day} {mese})"
        else:
            return f"{giorno_sett.capitalize()} {d.day} {mese}"
    else:
        d_inizio = dates[0]
        d_fine = dates[-1]
        mese_inizio = pack.months[d_inizio.month - 1]
        mese_fine = pack.months[d_fine.month - 1]

        if d_inizio.month == d_fine.month:
            start_str = str(d_inizio.day)
            end_str = f"{d_fine.day} {mese_fine}"
        else:
            start_str = f"{d_inizio.day} {mese_inizio}"
            end_str = f"{d_fine.day} {mese_fine}"

        return pack.temporal["from_to"].format(start=start_str, end=end_str)
